// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT2kQVMYiiDerYvgnNAnvny7IVR24YYeI',
    appId: '1:479932953791:web:fffb831c09b737f47c020a',
    messagingSenderId: '479932953791',
    projectId: 'evently-84877',
    authDomain: 'evently-84877.firebaseapp.com',
    storageBucket: 'evently-84877.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1ni7ga2kw_HBrdSq65BAB51nDsNwz_uU',
    appId: '1:479932953791:android:5acc4c5bbb7fb28b7c020a',
    messagingSenderId: '479932953791',
    projectId: 'evently-84877',
    storageBucket: 'evently-84877.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByyKSLV6OsPRQLdXkr8DGX0-l0QI70zN4',
    appId: '1:479932953791:ios:f8ac00597cb668847c020a',
    messagingSenderId: '479932953791',
    projectId: 'evently-84877',
    storageBucket: 'evently-84877.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );
}
